{{- if .Values.flower.enabled -}}
# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.flower.nameOverride | default (include "helm-edp.fullname" .) }}
  labels:
    {{- include "helm-edp.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.flower.replicas }}
  selector:
    matchLabels:
      {{- include "helm-edp.flower.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-edp.flower.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-edp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-redis
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: redis:alpine
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: edp-celery-secrets
                  key: CELERY_BACKEND_URL
          command:
            - sh
            - -c
            - |
                if [ -z "$REDIS_URL" ]; then
                  echo "Environment variable REDIS_URL is not set. Skipping wait-for-redis init container.";
                  exit 1
                else
                  REDIS_URL_OBFUSCATED=$(echo $REDIS_URL | sed -e 's|//.*:.*@|//********:********@|')
                  until redis-cli -u $REDIS_URL ping | grep -q PONG; do
                    echo "waiting for redis server $REDIS_URL_OBFUSCATED to be ready...";
                    sleep 2;
                  done;
                fi;
      containers:
        - name: {{ .Values.flower.nameOverride }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{ if .Values.alternateTagging }}
          image: {{ .Values.flower.repository }}:{{ .Values.flower.name }}_{{ .Values.flower.tag | default .Chart.AppVersion }}
          {{ else }}
          image: {{ .Values.flower.repository }}/{{ .Values.flower.name }}:{{ .Values.flower.tag | default .Chart.AppVersion }}
          {{ end }}
          imagePullPolicy: {{ .Values.flower.pullPolicy }}
          command:
            {{- range $index, $element := splitList " " .Values.flower.command }}
            - {{ $element | quote }}
            {{- end }}
          env:
          {{- if .Values.proxy.httpProxy }}
            - name: http_proxy
              value: {{ .Values.proxy.httpProxy }}
          {{- end }}
          {{- if .Values.proxy.httpsProxy }}
            - name: https_proxy
              value: {{ .Values.proxy.httpsProxy }}
          {{- end }}
          {{- if .Values.proxy.noProxy }}
            - name: no_proxy
              value: {{ include "helm-edp.noProxyWithContainers" . | quote }}
          {{- end }}
          {{- if .Values.flower.environment }}
            {{- toYaml .Values.flower.environment | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 5555
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.flower.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
