{{- if index .Values "app-monitors" "enabled" }}
# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tei-embedding-svc
  labels:
    release: {{.Release.Name}}
spec:
  namespaceSelector:
    matchNames:
    - chatqa
  selector:
    matchLabels:
      app.kubernetes.io/instance: tei
  endpoints:
  - port: "tei"
{{- end }}
