# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  embedding-mosec-model-server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: embedding-mosec:cpu
    container_name: embedding-mosec-model-server
    ports:
      - "${MOSEC_PORT}:8000"
    environment:
      HF_TOKEN: ${HF_TOKEN}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      MOSEC_MODEL_NAME: ${MOSEC_MODEL_NAME}
      MOSEC_AMP_DTYPE: ${MOSEC_AMP_DTYPE}
      MOSEC_DEVICE_TYPE: cpu
      MOSEC_MAX_BATCH_SIZE: ${MOSEC_MAX_BATCH_SIZE}
      MOSEC_MAX_WAIT_TIME: ${MOSEC_MAX_WAIT_TIME}
    cap_add:
      - SYS_NICE
    runtime: runc
    ipc: host

  embedding_usvc:
    build:
      context: ../../../../../../
      dockerfile: ./comps/embeddings/impl/microservice/Dockerfile
      target: ${EMBEDDING_CONNECTOR}
    container_name: embedding-mosec-microservice
    environment:
      NO_PROXY: ${NO_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      EMBEDDING_CONNECTOR: ${EMBEDDING_CONNECTOR}
      EMBEDDING_MODEL_NAME: ${MOSEC_MODEL_NAME}
      EMBEDDING_MODEL_SERVER: mosec
      EMBEDDING_MODEL_SERVER_ENDPOINT: http://localhost:${MOSEC_PORT}
    ipc: host
    runtime: runc
    network_mode: host
    restart: unless-stopped
    depends_on:
      - embedding-mosec-model-server
