# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  llm-vllm-model-server:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: vllm:cpu
    container_name: llm-vllm-model-server
    ports:
      - "${LLM_VLLM_PORT}:80"
    volumes:
      - "./data:/data"
    user: "1000:1000"
    environment:
      HF_TOKEN: ${HF_TOKEN}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      VLLM_CPU_KVCACHE_SPACE: ${VLLM_CPU_KVCACHE_SPACE}
    ipc: host
    command: "--model $LLM_VLLM_MODEL_NAME \
              --device cpu \
              --tensor-parallel-size $VLLM_TP_SIZE \
              --pipeline-parallel-size $VLLM_PP_SIZE \
              --dtype $VLLM_DTYPE --max-num-seqs $VLLM_MAX_NUM_SEQS \
              --max-model-len $VLLM_MAX_MODEL_LEN \
              --download_dir /data \
              --host 0.0.0.0 --port 80"

  llm_usvc:
    build:
      context: ../../../../../../
      dockerfile: ./comps/llms/impl/microservice/Dockerfile
    image: opea/llm:latest
    container_name: llm-vllm-microservice
    ipc: host
    runtime: runc
    network_mode: host
    environment:
      HTTPS_PROXY: ${HTTPS_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      LLM_CONNECTOR: ${LLM_CONNECTOR}
      LLM_MODEL_NAME: ${LLM_VLLM_MODEL_NAME}
      LLM_MODEL_SERVER: "vllm"
      LLM_MODEL_SERVER_ENDPOINT: http://localhost:${LLM_VLLM_PORT}
      NO_PROXY: ${NO_PROXY}
    restart: unless-stopped
    depends_on:
      - llm-vllm-model-server
