# Identity provider OIDC config
auth:
  realm: EnterpriseRAG
  client_id: EnterpriseRAG-oidc-backend
  resource_registration_endpoint: "https://keycloak.auth.svc/realms/EnterpriseRAG/authz/protection/resource_set"
  token_endpoint: "https://keycloak.auth.svc/realms/EnterpriseRAG/protocol/openid-connect/token"

endpoints:
  - name: chatqna
    namespace: chatqa
    hostname: erag.com
    path: /api/v1/chatqna
    backend_service: router-service
    service_port: 8080
    service_path: /
    rate_limit_count: 10
    permissions:
      - "admin#admin-access"
      - "user#user-access"
  - name: fingerprint-append
    namespace: fingerprint
    hostname: erag.com
    path: /v1/system_fingerprint/append_arguments
    service_port: 6012
    backend_service: fingerprint-svc
    service_path: /v1/system_fingerprint/append_arguments
    rate_limit_count: 30
    permissions:
      - "admin#admin-access"
  - name: fingerprint-change
    namespace: fingerprint
    hostname: erag.com
    path: /v1/system_fingerprint/change_arguments
    service_port: 6012
    backend_service: fingerprint-svc
    service_path: /v1/system_fingerprint/change_arguments
    rate_limit_count: 30
    permissions:
      - "admin#admin-access"
  - name: edp
    namespace: edp
    hostname: erag.com
    path: /api/v1/edp/*
    backend_service: edp-backend
    service_port: 5000
    rate_limit_count: 120
    service_regex:
      - ^/api/v1/edp/links$
      - /api/links
      - ^/api/v1/edp/link/([0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12})$
      - /api/link/$1
      - ^/api/v1/edp/link/([0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12})/retry$
      - /api/link/$1/retry
      - ^/api/v1/edp/link/([0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12})/task$
      - /api/link/$1/task
      - ^/api/v1/edp/files$
      - /api/files
      - ^/api/v1/edp/file/([0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12})$
      - /api/file/$1
      - ^/api/v1/edp/file/([0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12})/retry$
      - /api/file/$1/retry
      - ^/api/v1/edp/file/([0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12})/task$
      - /api/file/$1/task
      - ^/api/v1/edp/list_buckets$
      - /api/list_buckets
      - ^/api/v1/edp/file/([0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12})/extract$
      - /api/file/$1/extract
      - ^/api/v1/edp/retrieve$
      - /api/retrieve
      - ^/api/v1/edp/presignedUrl$
      - /api/presignedUrl
      - ^/api/v1/edp/files/sync
      - /api/files/sync
    permissions:
      - "admin#admin-access"

endpoints_api:
  - name: k8s-api-watcher-chatqa
    namespace: default
    path: /api/v1/chatqa/status
    backend_service: kubernetes
    rate_limit_count: 30
    service_port: 443
    scheme: https
    service_path: /apis/gmc.opea.io/v1alpha3/namespaces/chatqa/gmconnectors/chatqa/status
    permissions:
      - "admin#admin-access"

upstreams:
  - name: kubernetes
    namespace: default
    scheme: https
