# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "3.8"

services:
  reranking-tei-model-server:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.6
    container_name: reranking-tei-model-server
    ports:
      - "${RERANKER_TEI_PORT}:80"
    volumes:
      - ./data:/data
    environment:
      NO_PROXY: ${NO_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      HF_TOKEN: ${HF_TOKEN}
      MAX_BATCH_TOKENS: ${MAX_BATCH_TOKENS}
    command: ["--model-id", "${MODEL_ID}"]
    runtime: runc
    ipc: host

  reranking_usvc:
    build:
      context: ../../../../../../
      dockerfile: ./comps/reranks/impl/microservice/Dockerfile
    container_name: reranking-tei-microservice
    ipc: host
    runtime: runc
    network_mode: host
    environment:
      NO_PROXY: ${NO_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      RERANKING_SERVICE_ENDPOINT: http://127.0.0.1:${RERANKER_TEI_PORT}
      RERANKING_MODEL_SERVER: "tei"
    restart: unless-stopped
    depends_on:
      - reranking-tei-model-server
