# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
gmc:
  enabled: true
  namespace: "system"
  helm:
    version: "v3.16.1"
    chart_name: "gmc"
    chart_directory: "{{ playbook_dir }}/../components/gmc/microservices-connector/helm"
    release_name: "gmc"
    chart_version: "1.1.0"
    default_values_file: "{{ playbook_dir }}/../components/gmc/microservices-connector/helm/values.yaml"
    default_resources_file: "{{ pipelines_dir }}/chatqa/resources-reference-cpu.yaml"
    default_model_config_file: "{{ pipelines_dir }}/chatqa/resources-model-cpu.yaml"
    tdx_resources_file: "{{ pipelines_dir }}/../components/gmc/microservices-connector/helm/resources-tdx.yaml"
  pvc:
    accessMode: ReadWriteOnce
    models:
      modelLlm:
        name: model-volume-llm
        storage: 100Gi
      modelEmbedding:
        name: model-volume-embedding
        storage: 20Gi
      modelReranker:
        name: model-volume-reranker
        storage: 10Gi

llm_model: "casperhansen/llama-3-8b-instruct-awq"
llm_model_gaudi: "mistralai/Mixtral-8x7B-Instruct-v0.1"
embedding_model_name: "BAAI/bge-base-en-v1.5"
reranking_model_name: "BAAI/bge-reranker-base"
