# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  embedding-ovms-model-server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: embedding-ovms:cpu
    container_name: embedding-ovms-model-server
    ports:
      - "${OVMS_PORT}:9000"
    volumes:
      - ./data/:/data
    environment:
      HF_TOKEN: ${HF_TOKEN}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      OVMS_MODEL_NAME: ${OVMS_MODEL_NAME}
    runtime: runc
    ipc: host

  embedding_usvc:
    build:
      context: ../../../../../../
      dockerfile: ./comps/embeddings/impl/microservice/Dockerfile
    container_name: embedding-ovms-microservice
    environment:
      NO_PROXY: ${NO_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      EMBEDDING_CONNECTOR: ${EMBEDDING_CONNECTOR}
      EMBEDDING_MODEL_NAME: ${OVMS_MODEL_NAME}
      EMBEDDING_MODEL_SERVER: ovms
      EMBEDDING_MODEL_SERVER_ENDPOINT: http://localhost:${OVMS_PORT}
    ipc: host
    runtime: runc
    network_mode: host
    restart: unless-stopped
    depends_on:
      - embedding-ovms-model-server
