# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
gmc:
  enabled: true
  namespace: "system"
  helm:
    version: "v3.16.1"
    chart_name: "gmc"
    chart_directory: "{{ playbook_dir }}/../components/gmc/microservices-connector/helm"
    release_name: "gmc"
    chart_version: "1.1.0"
    default_values_file: "{{ playbook_dir }}/../components/gmc/microservices-connector/helm/values.yaml"
    default_resources_file: "{{ pipelines_dir }}/chatqa/resources-reference-cpu.yaml"
